# Generated by Django 4.1.4 on 2023-01-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Degree', models.CharField(max_length=100)),
                ('speciality', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('appointment_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor')),
            ],
        ),
    ]
